### 1. Array Creation

1.1 Create a 1-dimensional array of integers from 1 to 10.

In [1]:
import numpy as np

In [4]:
oneD_array = np.array(range(1,11))
oneD_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

1.2 Create a 2-dimensional array with random float values of shape (3, 4).

In [7]:
twoD_array = np.random.rand(3,4)
twoD_array

array([[0.89886504, 0.61365632, 0.29007076, 0.54069342],
       [0.86757533, 0.7178239 , 0.38437153, 0.56131151],
       [0.77628079, 0.86102461, 0.24389747, 0.88760232]])

In [8]:
twoD_array.shape

(3, 4)

1.3 Create a 3-dimensional array of zeros with shape (2,3,4)

In [9]:
threeD_array = np.zeros((2,3,4))
threeD_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
threeD_array.shape

(2, 3, 4)

### 2. Array Operations

2.1 Given two 1-dimensional arrays, perform element-wise addition,
subtraction, multiplication, and division.

In [3]:
import numpy as np
array_1 = np.array([7,3,9])

In [4]:
array_2 = np.array([5,2,8])

In [7]:
addition = array_1 + array_2
addition

array([12,  5, 17])

In [8]:
subtraction = array_1 - array_2
subtraction

array([2, 1, 1])

In [9]:
multiplication = array_1 * array_2
multiplication

array([35,  6, 72])

In [10]:
division = array_1 / array_2
division

array([1.4  , 1.5  , 1.125])

2.2 Calculate the mean, median, and standard deviation of a given 1-
dimensional array.

In [18]:
array_1 = np.array(range(1,9))
array_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
mean = np.mean(array_1)
mean

4.5

In [20]:
median = np.median(array_1)
median

4.5

In [21]:
sd = np.std(array_1)
sd

2.29128784747792

2.3 Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [26]:
array_1 = np.random.rand(1,12)
array_1

array([[0.04969304, 0.85137706, 0.79321343, 0.42064421, 0.07160265,
        0.99489767, 0.8310346 , 0.21847978, 0.02659855, 0.79023051,
        0.68567983, 0.55376146]])

In [27]:
reshape = array_1.reshape(3,4)
reshape

array([[0.04969304, 0.85137706, 0.79321343, 0.42064421],
       [0.07160265, 0.99489767, 0.8310346 , 0.21847978],
       [0.02659855, 0.79023051, 0.68567983, 0.55376146]])

### 3. Array Indexing and Slicing

3.1 Extract the first row and last column of a 2-dimensional array.

In [28]:
twoD = np.array([[2,6,3],[7,2,9]])
twoD

array([[2, 6, 3],
       [7, 2, 9]])

In [34]:
first_row = twoD[0,:]
first_row

array([2, 6, 3])

In [35]:
last_column = twoD[:,-1]
last_column

array([3, 9])

3.2 Reverse the order of elements in a 1-dimensional array.

In [36]:
oneD = np.array(range(1,7))
oneD

array([1, 2, 3, 4, 5, 6])

In [40]:
reverse = oneD[::-1]
reverse

array([6, 5, 4, 3, 2, 1])

3.3 Select elements from a 2-dimensional array that satisfy a specific
condition (e.g., values greater than a certain threshold).

In [41]:
twoD = np.arange(7)
twoD

array([0, 1, 2, 3, 4, 5, 6])

In [42]:
greater = twoD[twoD >4]
greater

array([5, 6])

### Array Broadcasting

4.1 Add a scalar value to each element of a 2-dimensional array.

In [47]:
twoD = np.array([[3,2,5],[7,12,5]])
twoD

array([[ 3,  2,  5],
       [ 7, 12,  5]])

In [50]:
value = 10
result = twoD + value
result

array([[13, 12, 15],
       [17, 22, 15]])

4.2 Multiply a 1-dimensional array with a 2-dimensional array, leveraging
NumPy's broadcasting rules.

In [52]:
array1 = np.array([1,6,3])
array1

array([1, 6, 3])

In [53]:
array2 = np.array([[5,3,2],[9,12,6]])
array2

array([[ 5,  3,  2],
       [ 9, 12,  6]])

In [54]:
multiply = array1 * array2
multiply

array([[ 5, 18,  6],
       [ 9, 72, 18]])

### Linear Algebra

5.1 Calculate the dot product of two 1-dimensional arrays.

In [55]:
array1 = np.array([2,8,21])
array1

array([ 2,  8, 21])

In [57]:
array2 = np.array([5,12.5,6])
array2

array([ 5. , 12.5,  6. ])

In [63]:
dot_product = array1.dot(array2)
dot_product

236.0

5.2 Compute the matrix multiplication of two 2-dimensional arrays.

In [64]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [65]:
mat1 = np.mat(array1)
mat1

matrix([[1, 2],
        [3, 4]])

In [67]:
array2 = np.array([[5,6],[7,8]])
array2

array([[5, 6],
       [7, 8]])

In [68]:
mat2 = np.mat(array2)
mat2

matrix([[5, 6],
        [7, 8]])

In [69]:
matMul = mat1 * mat2
matMul

matrix([[19, 22],
        [43, 50]])

5.3 Find the inverse and determinant of a square matrix.

In [70]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [71]:
matrix1 = np.mat(array1)
matrix1

matrix([[1, 2],
        [3, 4]])

In [73]:
determinant = np.linalg.det(matrix1)
determinant

-2.0000000000000004

In [74]:
inverse = np.linalg.inv(matrix1)
inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])